apiVersion: v1
kind: Service
metadata:
  name: payment-worker
  labels:
    app.kubernetes.io/name: payment-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: payment-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
