#!/usr/bin/env python3
"""Open or reuse the trusted Homebrew tap bump for a published korvid release."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from version_format import UNSUPPORTED_VERSION, is_supported_release_version

FORMULA_PATH = Path("Formula/korvid.rb")
RELEASE_PR_BODY = (
    "Generated by the korvid release workflow from the uv.lock that v{version} was tested against."
)
_URL_VERSION = re.compile(r'url "[^"]*/korvid-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz"')
_TEST_VERSION = re.compile(
    r'assert_match "([0-9]+\.[0-9]+\.[0-9]+)", shell_output\("#\{bin\}/korvid --version"\)'
)
_URL_USERINFO = re.compile(r"([A-Za-z][A-Za-z0-9+.-]*://)[^\s/?#]*@")


class CommandRunner(Protocol):
    """Call an external command and return stdout."""

    def __call__(self, argv: list[str], *, cwd: Path | None = None) -> str: ...


class HandoffError(RuntimeError):
    """Raised when the Homebrew tap handoff cannot proceed safely."""


@dataclass(frozen=True)
class UpdateResult:
    """Result of a tap update attempt."""

    status: str
    branch: str
    pr_number: int | None = None


def _sanitize_text(text: str) -> str:
    # Git tokens may occupy either userinfo field; do not parse untrusted error URLs.
    return _URL_USERINFO.sub(r"\1***@", text)


def _validate_clone_source(clone_source: str) -> None:
    if _URL_USERINFO.search(clone_source) is None:
        return
    raise HandoffError(
        f"tap clone source must not embed credentials: {_sanitize_text(clone_source)}"
    )


def _run_command(argv: list[str], *, cwd: Path | None = None) -> str:
    result = subprocess.run(
        argv,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        details = _sanitize_text(
            "\n".join(line for line in (result.stdout.strip(), result.stderr.strip()) if line)
            or f"command exited with status {result.returncode}"
        )
        raise HandoffError(f"{_sanitize_text(' '.join(argv))} failed:\n{details}")
    return result.stdout.strip()


def _version_key(version: str) -> tuple[int, int, int]:
    if not is_supported_release_version(version):
        raise HandoffError(UNSUPPORTED_VERSION)
    major, minor, patch = version.split(".")
    return int(major), int(minor), int(patch)


def _formula_version(formula_text: str) -> str:
    url_match = _URL_VERSION.search(formula_text)
    if url_match is None:
        raise HandoffError("formula must contain a single url version anchor")
    test_match = _TEST_VERSION.search(formula_text)
    if test_match is None:
        raise HandoffError("formula must contain a single assert_match version anchor")
    url_version = url_match.group(1)
    test_version = test_match.group(1)
    _version_key(url_version)
    _version_key(test_version)
    if url_version != test_version:
        raise HandoffError(
            f"formula url version {url_version} and assert_match version {test_version} disagree"
        )
    return url_version


def _read_formula_version(path: Path) -> str | None:
    if not path.is_file():
        return None
    return _formula_version(path.read_text(encoding="utf-8"))


def _git(run: CommandRunner, repo: Path, *args: str) -> str:
    return run(["git", *args], cwd=repo)


def _remote_branch_exists(repo: Path, branch: str) -> bool:
    # The stdout-only runner cannot distinguish no match (2) from transport errors.
    probe = subprocess.run(
        ["git", "ls-remote", "--exit-code", "--heads", "origin", branch],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
    )
    if probe.returncode == 0:
        return True
    if probe.returncode == 2 and not probe.stdout.strip():
        return False
    details = _sanitize_text(
        "\n".join(line for line in (probe.stdout.strip(), probe.stderr.strip()) if line)
    )
    raise HandoffError(f"git ls-remote failed:\n{details or 'unknown error'}")


def _github_user_id(run: CommandRunner, bot_login: str) -> int:
    raw = run(["gh", "api", f"users/{bot_login}"])
    payload = json.loads(raw)
    if not isinstance(payload, dict):
        raise HandoffError("gh api users lookup did not return a JSON object")
    user_id = payload.get("id")
    if not isinstance(user_id, int) or user_id <= 0:
        raise HandoffError(f"gh api users/{bot_login} did not return a numeric id")
    return user_id


def _changed_paths_since_merge_base(
    run: CommandRunner, repo: Path, base_ref: str, head_ref: str
) -> tuple[str, ...]:
    merge_base = _git(run, repo, "merge-base", base_ref, head_ref).strip()
    if not merge_base:
        raise HandoffError(f"could not determine merge-base for {base_ref} and {head_ref}")
    names = _git(run, repo, "diff", "--name-only", f"{merge_base}..{head_ref}")
    return tuple(line for line in names.splitlines() if line)


def _is_shallow_repository(run: CommandRunner, repo: Path) -> bool:
    return _git(run, repo, "rev-parse", "--is-shallow-repository").strip() == "true"


def _fetch_retry_history(
    run: CommandRunner,
    repo: Path,
    *,
    base_branch: str,
    branch: str,
) -> None:
    if _is_shallow_repository(run, repo):
        _git(run, repo, "fetch", "--no-tags", "--unshallow", "origin", base_branch)
    _git(run, repo, "fetch", "--no-tags", "origin", f"{branch}:refs/remotes/origin/{branch}")


def _main_branch_result(
    *,
    main_version: str | None,
    target_version: tuple[int, int, int],
    version: str,
    base_branch: str,
    branch: str,
) -> UpdateResult | None:
    if main_version is None:
        return None
    if _version_key(main_version) > target_version:
        raise HandoffError(
            f"tap {base_branch} already carries korvid {main_version}; refusing to downgrade to {version}"
        )
    if _version_key(main_version) == target_version:
        return UpdateResult(status="noop", branch=branch)
    return None


def _repository_owner(tap_repository: str) -> str:
    owner, separator, _ = tap_repository.partition("/")
    if not separator or not owner:
        raise HandoffError(f"tap repository must be OWNER/REPO, got {tap_repository!r}")
    return owner


def _open_pr_number(
    run: CommandRunner,
    *,
    tap_repository: str,
    branch: str,
    base_branch: str,
    bot_login: str,
) -> int | None:
    owner = _repository_owner(tap_repository)
    raw = run(
        [
            "gh",
            "api",
            (f"repos/{tap_repository}/pulls?state=open&head={owner}:{branch}&base={base_branch}"),
        ]
    )
    payload = json.loads(raw)
    if not isinstance(payload, list):
        raise HandoffError("gh api pulls lookup did not return a JSON list")
    if not payload:
        return None
    if len(payload) != 1:
        raise HandoffError(f"expected exactly one open pull request for {branch}")
    pr = payload[0]
    if not isinstance(pr, dict):
        raise HandoffError("gh api pulls lookup did not return a JSON object in its list")
    number = pr.get("number")
    base = pr.get("base", {})
    head = pr.get("head", {})
    author = pr.get("user", {})
    base_ref = base.get("ref") if isinstance(base, dict) else None
    head_ref = head.get("ref") if isinstance(head, dict) else None
    author_login = author.get("login") if isinstance(author, dict) else None
    if base_ref != base_branch or head_ref != branch or not isinstance(number, int):
        raise HandoffError(f"existing pull request for {branch} does not target {base_branch}")
    if not isinstance(author_login, str) or not author_login:
        raise HandoffError(
            f"existing pull request for {branch} is missing a REST user.login author"
        )
    if author_login != bot_login:
        raise HandoffError(
            f"existing pull request for {branch} was opened by {author_login}, expected {bot_login}"
        )
    return number


def _create_pr(
    run: CommandRunner,
    *,
    tap_repository: str,
    branch: str,
    base_branch: str,
    version: str,
) -> int:
    url = run(
        [
            "gh",
            "pr",
            "create",
            "--repo",
            tap_repository,
            "--base",
            base_branch,
            "--head",
            branch,
            "--title",
            f"korvid {version}",
            "--body",
            RELEASE_PR_BODY.format(version=version),
        ]
    ).strip()
    match = re.search(r"/pull/([0-9]+)\Z", url)
    if match is None:
        raise HandoffError(f"could not determine pull request number from {url!r}")
    return int(match.group(1))


def _existing_branch_result(
    *,
    branch_version: str | None,
    branch_formula_text: str | None,
    generated_formula_text: str,
    target_version: tuple[int, int, int],
    version: str,
    branch: str,
    pr_number: int | None,
    run: CommandRunner,
    tap_repository: str,
    base_branch: str,
) -> UpdateResult | None:
    if branch_version is None:
        return None
    if _version_key(branch_version) > target_version:
        raise HandoffError(
            f"existing {branch} carries korvid {branch_version}; refusing to replace it with {version}"
        )
    if branch_version != version:
        return None
    if branch_formula_text != generated_formula_text:
        return None
    resolved_pr = (
        pr_number
        if pr_number is not None
        else _create_pr(
            run,
            tap_repository=tap_repository,
            branch=branch,
            base_branch=base_branch,
            version=version,
        )
    )
    return UpdateResult(
        status="reused" if pr_number is not None else "opened",
        branch=branch,
        pr_number=resolved_pr,
    )


def _stage_formula_update(run: CommandRunner, repo: Path, formula: Path) -> None:
    branch_formula = repo / FORMULA_PATH
    branch_formula.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(formula, branch_formula)
    _git(run, repo, "add", "--", FORMULA_PATH.as_posix())
    staged_paths = tuple(
        line for line in _git(run, repo, "diff", "--cached", "--name-only").splitlines() if line
    )
    if staged_paths != (FORMULA_PATH.as_posix(),):
        raise HandoffError(
            f"staged tap changes are {staged_paths!r}; expected only {FORMULA_PATH.as_posix()}"
        )


def _commit_formula_update(run: CommandRunner, repo: Path, *, version: str, bot_login: str) -> None:
    bot_user_id = _github_user_id(run, bot_login)
    _git(
        run,
        repo,
        "-c",
        f"user.name={bot_login}",
        "-c",
        f"user.email={bot_user_id}+{bot_login}@users.noreply.github.com",
        "commit",
        "-m",
        f"korvid {version}",
    )
    _git(run, repo, "push", "origin", f"HEAD:refs/heads/bump-korvid-{version}")


def update_homebrew_tap(
    *,
    version: str,
    formula: Path,
    bot_login: str,
    tap_repository: str = "hellices/homebrew-korvid",
    tap_clone_source: str | None = None,
    clone_dir: Path = Path("tap"),
    base_branch: str = "main",
    command_runner: CommandRunner = _run_command,
) -> UpdateResult:
    """Open or reuse the Homebrew tap pull request for *version*."""
    target_version = _version_key(version)
    formula_text = formula.read_text(encoding="utf-8")
    generated_version = _formula_version(formula_text)
    if generated_version != version:
        raise HandoffError(
            f"generated formula version {generated_version} does not match requested release version {version}"
        )
    if clone_dir.exists():
        raise HandoffError(f"{clone_dir} already exists; refusing to reuse a stale tap clone")

    branch = f"bump-korvid-{version}"
    clone_source = tap_clone_source or f"https://github.com/{tap_repository}.git"
    _validate_clone_source(clone_source)

    command_runner(["gh", "auth", "setup-git"])
    command_runner(
        [
            "git",
            "clone",
            "--depth",
            "1",
            "--branch",
            base_branch,
            "--single-branch",
            clone_source,
            str(clone_dir),
        ]
    )
    repo = clone_dir
    main_formula = repo / FORMULA_PATH
    main_result = _main_branch_result(
        main_version=_read_formula_version(main_formula),
        target_version=target_version,
        version=version,
        base_branch=base_branch,
        branch=branch,
    )
    if main_result is not None:
        return main_result

    if _remote_branch_exists(repo, branch):
        _fetch_retry_history(
            command_runner,
            repo,
            base_branch=base_branch,
            branch=branch,
        )
        changed_paths = _changed_paths_since_merge_base(
            command_runner, repo, f"origin/{base_branch}", f"origin/{branch}"
        )
        unexpected = [path for path in changed_paths if path != FORMULA_PATH.as_posix()]
        if unexpected:
            raise HandoffError(
                f"existing {branch} changes {unexpected!r}; safe retries may change only Formula/korvid.rb"
            )
        _git(command_runner, repo, "switch", "-c", branch)
        _git(command_runner, repo, "reset", "--hard", f"origin/{branch}")
    else:
        _git(command_runner, repo, "switch", "-c", branch)

    pr_number = _open_pr_number(
        command_runner,
        tap_repository=tap_repository,
        branch=branch,
        base_branch=base_branch,
        bot_login=bot_login,
    )

    existing_result = _existing_branch_result(
        branch_version=_read_formula_version(repo / FORMULA_PATH),
        branch_formula_text=(
            (repo / FORMULA_PATH).read_text(encoding="utf-8")
            if (repo / FORMULA_PATH).is_file()
            else None
        ),
        generated_formula_text=formula_text,
        target_version=target_version,
        version=version,
        branch=branch,
        pr_number=pr_number,
        run=command_runner,
        tap_repository=tap_repository,
        base_branch=base_branch,
    )
    if existing_result is not None:
        return existing_result

    _stage_formula_update(command_runner, repo, formula)
    _commit_formula_update(command_runner, repo, version=version, bot_login=bot_login)

    return UpdateResult(
        status="reused" if pr_number is not None else "opened",
        branch=branch,
        pr_number=pr_number
        if pr_number is not None
        else _create_pr(
            command_runner,
            tap_repository=tap_repository,
            branch=branch,
            base_branch=base_branch,
            version=version,
        ),
    )


def main(argv: list[str] | None = None, *, command_runner: CommandRunner = _run_command) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True)
    parser.add_argument("--formula", type=Path, default=Path("korvid.rb"))
    parser.add_argument("--bot-login", required=True)
    parser.add_argument("--tap-repository", default="hellices/homebrew-korvid")
    parser.add_argument("--tap-clone-source")
    parser.add_argument("--clone-dir", type=Path, default=Path("tap"))
    parser.add_argument("--base-branch", default="main")
    args = parser.parse_args(argv)

    try:
        result = update_homebrew_tap(
            version=args.version,
            formula=args.formula,
            bot_login=args.bot_login,
            tap_repository=args.tap_repository,
            tap_clone_source=args.tap_clone_source,
            clone_dir=args.clone_dir,
            base_branch=args.base_branch,
            command_runner=command_runner,
        )
    except (HandoffError, OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 1

    if result.status == "noop":
        print(f"tap {args.base_branch} already carries korvid {args.version}; leaving it unchanged")
    elif result.status == "reused":
        print(f"reused tap pull request #{result.pr_number} for {result.branch}")
    else:
        print(f"opened tap pull request #{result.pr_number} for {result.branch}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
